config/routes.rb
Rails.application.routes.draw do
  
  resources :departamentos
	#get "produtos" => "listaprodutos#index"
	resources :produtos, only: [:new, :create, :destroy, :edit, :update]
	root "produtos#index"
	get "/produtos/busca" =>"produtos#busca", as: :busca_produto
	#get "/produtos/new" => "listaprodutos#new"
	#post "/produtos" => "listaprodutos#create"
	#delete "/produtos/:id" => "listaprodutos#destroy", as: :produto
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento #O produto pertence a um departamento
  validates :quantidade, presence: true
  validates :nome, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
    
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
before_action :set_produto, only: [:edit, :update, :destroy]# a função set_produto vai ser a primeira 
# a ser chamada dentro das funçõs edit, update e destroy

  def index
    @produtos_por_nome = Produto.order :nome
    @produtos_por_preco = Produto.order(:preco).limit 3
  end

  def  busca
    @nome_a_buscar = params[:nome]
    @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"#Usamos o % % para buscar um termo
    #e não um número exato
  end

  def new
    @produto = Produto.new
    renderiza_new
  end

  def create
    valores = produto_params
    @produto = Produto.new valores
    
    if @produto.save
      flash[:notice] = "Produto Salvo com Sucesso!"
      redirect_to root_url
    else
      renderiza_new
    end
  end

  def destroy
      #set_produto
      @produto.destroy
      redirect_to root_url
  end

  def edit
    #set_produto
    renderiza :edit
  end

  def update
    #set_produto   
    valores = produto_params
    if @produto.update valores #observa cada valor permitido em valores e atualiza
      flash[:notice] = "Produto atualizado com sucesso!" #se atualizar exibe uma 
      redirect_to root_url #mensagem e redireciona para url raiz
    else
      renderiza :edit
    end    
  end
  
  private
  def renderiza_new
    @departamentos = Departamento.all
    render :new 
  end

  def renderiza(view)
    @departamentos = Departamento.all
    render view
  end

  def set_produto #busca produto por id
    id = params[:id]
    @produto = Produto.find(id)
  end

  def produto_params
    params.require(:produto).permit(:nome, :descricao, :preco, :quantidade, :departamento_id)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/listaprodutos_helper.rb
module ListaprodutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= nav_bar brand: "Só Camisetas", brand_link: root_url do%>
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

<%= form_for @produto do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :nome, class:"form-control"  %><br/>
  
  <%= f.label :descricao %>
  <%= f.text_area :descricao, class:"form-control", rows:4  %><br/>

  <div class="form-group">
    <%= f.label :departamento %>
    <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
  </div>
  
  <div class="form-inline">
    <div class="form-group">
      <%= f.label :quantidade %>
      <%= f.number_field :quantidade, step:1, class:"form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :preco %>
      <%= f.number_field :preco, step:0.01, class:"form-control" %>
    </div>
    <%= f.submit texto_da_acao, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
    <tr>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao %></td>
      <td><%= format("%.2f", produto.preco) %></td> <!-- format("%.2f", produto.preco) para formatar a exibição das casas decimais-->  
      <td><%= button_to "Remover",  produto, method: :delete, class: "btn btn-danger",
        data: {confirm:"Tem certeza que deseja excluir #{produto.nome}?"} %> </td>
     <td><%= link_to "Alterar", edit_produto_path(produto), class: "btn btn-default"%> </td>
    </tr>    

app/views/produtos/busca.html.erb
<table class = 'table table-striped'>
  <h4>Resultado da busca</h4>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Descrição</th>
      <th>Preço</th>      
    </tr>
  </thead>
  <tbody>
    <%= render partial: "produto", collection: @produtos %>
  </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: "form", locals: { texto_da_acao: "Atualizar Produto"}%>

app/views/produtos/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Lista de Produtos</title>
  </head>
  <body>
  <%if flash[:notice]%>
    <div class = "alert alert-success" role="alert">
      <%=flash[:notice]%>
    </div>
  <%end%>
    <table class = 'table table-striped'>
      <h4>Ordem Alfabética</h4>
      <thead>
        <tr>
          <th>Produto</th>
          <th>Descrição</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody>
        <%= render @produtos_por_nome %> <!--Ao renderizar o array @produtos_por_nome os elementos
        do array (produto1, produto2...) indicam que deve ser invocado o partial _produto -->
      </tbody>
    </table>
    <table class = 'table table-striped'>
      <h4>Top 3: mais baratos</h4>
      <thead>
        <tr>
          <th>Produto</th>
          <th>Descrição</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody>
        <%= render @produtos_por_preco %><!--Ao renderizar o array @produtos_por_preco os elementos
        do array (produto1, produto2...) indicam que deve ser invocado o partial _produto -->
      </tbody>
    </table>
    <%= link_to "Criar novo Produto", new_produto_path %>
  </body>
</html>

app/views/produtos/new.html.erb
<%= render partial: "form", locals: { texto_da_acao: "Criar Produto"}%>